### ISSUE TITLE
Invalid number when using comma as decimal separator

### ISSUE THREAD

**Issue by voldmaks** [danielo535/CustomWallet#1]
Hello. I wanted to use your plugin together with "another plugin". But the "other plugin" uses a comma as decimal separator, which causes the error "Invalid number". There is no option to change decimal separator in your plugin's config, so I decided to write you about this problem.

**Comment by danielo535** [comment]
> Hello. I wanted to use your plugin together with "another plugin". But the "other plugin" uses a comma as decimal separator, which causes the error "Invalid number". There is no option to change decimal separator in your plugin's config, so I decided to write you about this problem.

hello tomorrow I'll try to sort something out give me your discord

**Comment by voldmaks** [comment]
My nickname in Discord is " voldmaks ".
I hope you can find me by my nickname :D
